create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'agent' check (role in ('owner', 'creator', 'agent')),
  created_at timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  type text not null,
  operation text not null check (operation in ('Venta', 'Alquiler')),
  price numeric not null default 0,
  location text not null,
  area numeric not null default 0,
  beds integer not null default 0,
  baths integer not null default 0,
  tag text not null default 'Nueva',
  image_url text not null,
  description text not null default '',
  is_published boolean not null default true,
  is_featured boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0
);

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.property_images enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles
  for select to authenticated using (id = auth.uid());

drop policy if exists "Published properties are public" on public.properties;
create policy "Published properties are public" on public.properties
  for select using (is_published = true);

drop policy if exists "Published images are public" on public.property_images;
create policy "Published images are public" on public.property_images
  for select using (exists (select 1 from public.properties p where p.id = property_id and p.is_published = true));

drop policy if exists "Admins manage properties" on public.properties;
create policy "Admins manage properties" on public.properties
  for all to authenticated using (exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator'))) with check (exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator')));

drop policy if exists "Admins manage images" on public.property_images;
create policy "Admins manage images" on public.property_images
  for all to authenticated using (exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator'))) with check (exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator')));

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id, full_name, role) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email), 'agent');
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

insert into storage.buckets (id, name, public) values ('property-images', 'property-images', true) on conflict (id) do nothing;

drop policy if exists "Public property images" on storage.objects;
create policy "Public property images" on storage.objects for select using (bucket_id = 'property-images');

drop policy if exists "Admins upload property images" on storage.objects;
create policy "Admins upload property images" on storage.objects for insert to authenticated with check (bucket_id = 'property-images' and exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator')));

drop policy if exists "Admins update property images" on storage.objects;
create policy "Admins update property images" on storage.objects for update to authenticated using (bucket_id = 'property-images' and exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator'))) with check (bucket_id = 'property-images' and exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator')));

drop policy if exists "Admins delete property images" on storage.objects;
create policy "Admins delete property images" on storage.objects for delete to authenticated using (bucket_id = 'property-images' and exists (select 1 from public.profiles where id = auth.uid() and role in ('owner', 'creator')));
